### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by zachfi** [Axcient/freebsd-nfs-exporter#4]
Hello, thank you for this project.

I'm looking to run this on an IPv6 address, but I get the following.  May I request IPv6 support for this project please?

```
$ nfs-exporter -b "::0" -p 11111
thread 'main' panicked at 'can not parse listen addr: AddrParseError(())', src/main.rs:64:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by asomers-ax** [comment]
@xaque208 sorry I didn't notice this bug when you first filed it, but it should be fixed now.
